
# This file defines configurations for your Supabase project

project_id = "otxdnlfikoiafqshlydu"

[functions.create-subscription]
verify_jwt = true

[functions.process-payment-webhook]
verify_jwt = false

[functions.verify-subscriptions]
verify_jwt = false
