// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otxdnlfikoiafqshlydu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90eGRubGZpa29pYWZxc2hseWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzIzNTgsImV4cCI6MjA2MDQwODM1OH0.n9dPvfnnHxi80bBtSycmTwxeYW8X84lbbgK9uLrUxcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);